### ISSUE TITLE
After logging in I clicked on the submit link modal and got an error

### ISSUE THREAD

**Issue by earthlingworks** [SachaG/SidebarFeedback#10]
After login in I think the mouse cursor was focused on the URL field of the submit link modal (can't be sure) and I clicked on another area of the modal. This came up: http://cl.ly/3T1q1f2I3h1d

I could have clicked on the URL field and then off of it...don't remember exactly.

**Comment by SachaG** [comment]
Yes, when you unfocus the URL field it queries for a thumbnail, so if there's no URL it throws an error. I'll fix this so it only does this if you actually entered something in the field.
