### ISSUE TITLE
Control Label Vertical Alignment

### ISSUE THREAD

**Issue by Macca2805** [SachaG/SidebarFeedback#12]
The vertical alignment of some of the forms in the modals is slightly off. See my crude screenshots below.

![snip_20160629100458](https://cloud.githubusercontent.com/assets/5493721/16553187/697a6ad4-41f9-11e6-801c-aa84d67578e0.png)

![snip_20160629100428](https://cloud.githubusercontent.com/assets/5493721/16553194/77a09426-41f9-11e6-8dc4-38d70fee639d.png)

I assume you are using Bootstrap in some form... Bootstrap offers a class to add to your form tag called `form-horizontal`. This adds a small amount of padding to the `label.control-label` class to better align the labels vertically.

[Bootstrap - Forms Horizontal](https://getbootstrap.com/css/#forms-horizontal)

It also aligns the label text to the right so you may want to have an override or just work out the padding yourself.

**Comment by SachaG** [comment]
Thanks, I'll look into it :)

**Comment by Macca2805** [comment]
The new sidebar is great by the way, well done!
