### ISSUE TITLE
RSS feed shows more than 5 picks a day since redesign

### ISSUE THREAD

**Issue by piersolenski** [SachaG/SidebarFeedback#16]
Have used Sidebar since it's inception, long term fan! However part of it's appeal was always the curated nature of the 5 picks, which was a refreshing change from the overload of the average feed. Since the redesign the RSS feed has bloated to all of the suggestions as well. Please change it back, or at least introduce a separate feed for this! Thanks!

**Comment by SachaG** [comment]
Should be fixed now. If it's still not working for you you can also try http://sidebar.io/feed.xml?view=featured
