### ISSUE TITLE
Inbox feed stopped coming through

### ISSUE THREAD

**Issue by Mattapeh** [SachaG/SidebarFeedback#18]
Since the nice new update to the website and email designs I have stopped receiving daily new links which is a bit of a shame since I like to read them daily.

I have resubscribed and have yet to see if I will get a daily feed again but I thought I'd report this anyway in the case that the update wasn't supposed to have stopped daily emails being sent through

**Comment by SachaG** [comment]
Maybe they're in your spam folder?

(btw where is your avatar from?)

**Comment by Mattapeh** [comment]
Nope I have checked, they simply stopped coming through on the 5th June and then none for the last couple of days - I have all my emails from sidebar.io go to it's own folder on gmail so I can read them when I get a time to catch up.

My avatar is from nothing special, it is merely something I did on my old website many years ago.

EDIT: Found the issue - it was a fault on my end - no need to worry!
