### ISSUE TITLE
.posts-item-title-link flickers as you hover

### ISSUE THREAD

**Issue by LucPestille** [SachaG/SidebarFeedback#2]
Because .posts-item-title-link defaults to inline, and the line height is >1, as I hover over the links in the main list (noticable mainly in the current hero day), the colour change flickers as my mouse hits dead spots inbetween the lines.

Changing .posts-item-title-link to display:block; will fix that issue, but you'll lose the ability for the domain to follow directly on from the title, which you probably wanted to keep.

Personally I think the trade-off is worth it, and having the domain/tick/sponsored tag below the link is worth it, and makes the headlines a tiny bit more scannable...

**Comment by SachaG** [comment]
Oh hmm yeah that's annoying… why did you have to make me notice!

I do want to keep the domain on the same line to maximize information density. So I don't think I can fix this. Let's hope nobody else notices ;)
