### ISSUE TITLE
Sidebar app doesn't update on iPhone 6+

### ISSUE THREAD

**Issue by zalel** [SachaG/SidebarFeedback#22]
I have an iPhone 6+ running iOS 9.3.2. For a long time it has

**Comment by zalel** [comment]
I have an iPhone 6+ running iOS 9.3.2. For a long time your app has failed to update. The newest item is May 23. I have deleted and reinstalled more than once, to bo effect. 

What can I do?

**Comment by SachaG** [comment]
By Sidebar app do you mean the website?

**Comment by zalel** [comment]
No, I meant the iOS app.

**Comment by SachaG** [comment]
There's no official Sidebar app so it's probably something someone else made using the API. I can't really help you, sorry…

**Comment by zalel** [comment]
Oh. Oh well, thanks anyway...

Nicky McCatty
signify.Design 
617.433.9085 

Nicky McCatty
signify.Design 
617.433.9085
