### ISSUE TITLE
Sticky header causes horizontal scrollbar

### ISSUE THREAD

**Issue by LucPestille** [SachaG/SidebarFeedback#3]
The sticky header is causing a permanent horizontal scrollbar, because of the .nav .header-link a having padding: 10px; - that padding isn't required because its parent has got the necessary flex properties to center the icon (at least in browsers that understand it).

That padding may be required in other, lesser browsers, but could sit behind a conditional somewhere.

FF 45.2.0, Win 10

**Comment by SachaG** [comment]
Good catch, I added that padding just recently. Fixing it.
