### ISSUE TITLE
GraphQL error

### ISSUE THREAD

**Issue by pburtchaell** [SachaG/SidebarFeedback#44]
When  I try to subscribe to the email, I get the following error:

```
GraphQL error: {"id":"newsletter.subscription_failed"}
```
Screenshot:
<img width="1440" alt="screen shot 2017-06-04 at 15 40 49" src="https://cloud.githubusercontent.com/assets/3857324/26765975/37ccec82-493c-11e7-8da6-c4e6a9896819.png">

**Comment by SachaG** [comment]
You can try subscribing through this link instead: http://sidebar.us2.list-manage1.com/subscribe?u=b5af47765edbd2fc173dbf27a&id=9abeab36bb
