### ISSUE TITLE
500 server error for all links in Wednesday's and Thursday's issues, 6/21 & 6/22

### ISSUE THREAD

**Issue by su-narthur** [SachaG/SidebarFeedback#46]
I'm seeing these errors whether I try to open the links from my email or from Sidebar.io. Links in previous issues still work fine.

**Comment by neonhoney** [comment]
Same, but happening to me on current and previous issues.

**Comment by SachaG** [comment]
Thanks, I'll look into it. It might be some temporary problem so I would suggest trying a couple times whenever you run into this kind of issue.

**Comment by su-narthur** [comment]
@SachaG Thanks for looking into it. I tried several times before reporting. It looks like it's all fixed this morning.
