### ISSUE TITLE
Having trouble submitting

### ISSUE THREAD

**Issue by roblevintennis** [SachaG/SidebarFeedback#48]
I'm not sure if this is due to the update, I've successfully submitted last week, but I'm getting the following when I try now (note the empty pink alert):

![image](https://user-images.githubusercontent.com/142403/28195965-6c1ba962-6802-11e7-9a60-0c7c67343fbf.png)

If it's helpful to debug, the article I'm trying to submit is:
https://medium.com/@roblevintennis/illustration-teardowns-italian-illustrators-cd843d2d5153

**Comment by SachaG** [comment]
Should be fixed now :)

**Comment by roblevintennis** [comment]
awesome, I just confirmed 👍
