### ISSUE TITLE
[suggestion] Consider Killing The Cards Screen

### ISSUE THREAD

**Issue by TedGoas** [SachaG/SidebarFeedback#5]
The homepage _looks_ nice, but I don't think it provides enough value to stay where it is. The "main" screen provides the same information, plus more, without being overwhelming. It provides:
- The same 5 links from the current day in an easy-to-consume manner.
- Non featured link from the current day.
- More links from more days.
- Wayfinding systems.
- A design that's more familiar to the current design (if that's a good thing).

⬇ This would make a great homepage ⬇
<img width="1183" alt="screen shot 2016-06-29 at 8 16 53 am" src="https://cloud.githubusercontent.com/assets/1172461/16451757/e3d2df12-3dd2-11e6-928e-3ad4adc22284.png">

**Comment by SachaG** [comment]
Well, I actually did start off with something more similar to your screenshot. But I decided it wasn't really distinctive enough, it looked like any other links directory out there. 

So the idea behind the current design is that it would stand out more, and be more memorable. Having the header at the bottom of the page means it might not immediately be obvious that you can scroll down, so people can "discover" that feature later on. 

And in the meantime the main top area can serve as a homepage of sorts, something you can set as your "new tab" page or get in the habit of opening up every morning. 

Not sure how well it'll work, and I agree it duplicates content, but I want to try it out :)

**Comment by SachaG** [comment]
(Closing this for now, may reopen it if I decide to rethink the design. I definitely appreciate the feedback though!)

**Comment by faelsoto** [comment]
I totally agree with @TedGoas, the main screen now looks weird, and it's not consitent with the design.

Honestly, as a really big fan of sidebar.io, I'm not digging this direction and I hope you can keep the old version the way it is on another subdomain. Even without the main page, I think the categories as well as the calendar are just _too_ much—I want five design links every day. Even if I'm out of town for a few days (or a month), I'm 30 or so clicks away to catch up.

Also, I'm really missing the keyboard shortcuts and I think this new site takes too much to load. 

To wrap things up, first of all, I'd like to thank you for such a hard work both on creating and updating sidebar's content, and for such a great work on the new design, but as a big fan, I respectfully don't agree with the design.

**Comment by SachaG** [comment]
@faelsoto Well compared to the previous version, now you don't even have to click to see links from previous days, you can just scroll down. So in theory it should be easier?

I'm surprised you say it loads slower than before though, how long does it take for you?
