### ISSUE TITLE
Can't subscribe

### ISSUE THREAD

**Issue by lataylor2** [SachaG/SidebarFeedback#55]
Tried in latest versions of Chrome and Safari on Mac. Enter email, hit button, the spinner just spins endlessly

**Comment by SachaG** [comment]
You can try
http://sidebar.us2.list-manage1.com/subscribe?u=b5af47765edbd2fc173dbf27a&id=9abeab36bb

**Comment by lataylor2** [comment]
That worked. Thank you.
