### ISSUE TITLE
[suggestion] Tagging new articles is hard 

### ISSUE THREAD

**Issue by TedGoas** [SachaG/SidebarFeedback#6]
Sidebar has tags/categories. Awesome! I would love to use those when submitting new articles, but there's no way to tell what's available when submitting a new article:

<img width="475" alt="screen shot 2016-06-29 at 8 31 10 am" src="https://cloud.githubusercontent.com/assets/1172461/16452035/5b55fa78-3dd4-11e6-990b-0d01dddb03ed.png">

Would it make sense to list out tags ⬇ like the website does? Or use autocomplete on this text field?

<img width="291" alt="screen shot 2016-06-29 at 8 31 20 am" src="https://cloud.githubusercontent.com/assets/1172461/16452010/40e40720-3dd4-11e6-8ac3-046c5e2bb9bb.png">

**Comment by SachaG** [comment]
The field does use autocomplete? Is it not working for you?

**Comment by TedGoas** [comment]
My bad, it _does_ work after typing two characters. Technical issues aside, I still think the experience is a bit awkward since there's no indication as to what would be auto-completed. I could see getting used to it after some use, though. Maybe I'm just used to the current version...

**Comment by SachaG** [comment]
Yeah I'm just not quite sure how to integrate it with the UI. Maybe I can change it so that the autocomplete starts right away though, I'll have to see about that.

**Comment by TedGoas** [comment]
Maybe something like one of [Chosen's Multiple Select's](https://harvesthq.github.io/chosen/)? Could build upon the existing experience? I dunno, this is starting to sound like an enhancement rather than a bug.

![screen shot 2016-06-29 at 9 04 01 pm](https://cloud.githubusercontent.com/assets/1172461/16473635/25b47232-3e3d-11e6-8075-c592f2b05d68.png)

**Comment by SachaG** [comment]
I set it to trigger after one character, that should help a little. I can't really use a different autofill component for now, but if anything better comes along I'll reconsider.
