### ISSUE TITLE
Layout fails a bit with multi-line headings

### ISSUE THREAD

**Issue by teddyzetterlund** [SachaG/SidebarFeedback#8]
![screen shot 2016-06-30 at 13 40 17](https://cloud.githubusercontent.com/assets/1955/16487009/6f397322-3ec8-11e6-9fab-595922c0f395.png)

**Comment by SachaG** [comment]
Oh interesting, which browser/OS is this? This is what I see (Chrome Mac OS): 

![https://s3.amazonaws.com/f.cl.ly/items/0e343j160v2T3q331a23/Screen%20Shot%202016-06-30%20at%208.47.03%20PM.png?v=dddf29ac](https://s3.amazonaws.com/f.cl.ly/items/0e343j160v2T3q331a23/Screen%20Shot%202016-06-30%20at%208.47.03%20PM.png?v=dddf29ac)

**Comment by teddyzetterlund** [comment]
Ah, sorry. You're right on that. It's Safari 9.1.1 on El Capitan (10.11.5).

I was hoping to use _flexbox_ extensively myself recently and ran into some issues with Safari. Can't remember exactly what, but its support isn't yet perfect it would seem.

**Comment by SachaG** [comment]
Yeah flexbox behaves a bit weirdly sometimes. A flex-shrink: 0 fixed it.
