### ISSUE TITLE
Post approval email not displaying properly

### ISSUE THREAD

**Issue by TedGoas** [SachaG/SidebarFeedback#9]
This is what I see in Apple Mail:

![screen shot 2016-06-30 at 1 07 23 pm](https://cloud.githubusercontent.com/assets/1172461/16497154/9edcb666-3ec3-11e6-8c7d-ac1c862c6d6a.png)

**Comment by SachaG** [comment]
You're right, I just noticed that yesterday as well. I'll fix it.
